# Generated by Django 5.2 on 2025-06-16 20:53

import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', validators=[forum.models.validate_image], verbose_name='Зображення'),
        ),
    ]
